export const navItems = [
  "今日必读",
  "论文雷达",
  "项目实验室",
  "产品观察",
  "我的素材库",
  "学习计划",
];

export const categories = [
  "全部",
  "大模型",
  "AI Agent",
  "多模态",
  "机器人/具身智能",
  "AI安全",
  "AI产品",
  "开源项目",
  "论文",
];

export const articles = [
  {
    id: 1,
    title: "Google DeepMind 发布机器人 VLA 新进展，强化长程任务泛化",
    source: "DeepMind Blog",
    time: "08:20",
    category: "机器人",
    credibility: 96,
    heat: 91,
    relevance: 98,
    summary: "模型把视觉、语言和动作序列统一建模，展示了更稳的跨场景操作能力。",
    why: "适合追踪具身智能申请方向，也能转化为 VLA/模仿学习综述素材。",
    actions: ["读论文", "写笔记", "做项目", "收藏"],
    knowledge: ["VLA", "Imitation Learning", "Robot Policy"],
    project: "复现一个桌面抓取任务的数据标注与策略评估小实验",
  },
  {
    id: 2,
    title: "Hugging Face Daily Papers 热榜出现低成本多模态 Agent 论文",
    source: "HF Papers",
    time: "09:05",
    category: "AI Agent",
    credibility: 88,
    heat: 94,
    relevance: 92,
    summary: "论文尝试用工具调用和视觉状态压缩降低多模态 Agent 推理成本。",
    why: "既能服务科研计划，也能形成 AI 产品经理视角的成本分析案例。",
    actions: ["读论文", "看代码", "写笔记", "收藏"],
    knowledge: ["Tool Use", "Vision Agent", "Cost Evaluation"],
    project: "做一个网页浏览 Agent 的多步骤任务成功率对比表",
  },
  {
    id: 3,
    title: "NVIDIA 开源机器人仿真工具链更新，强调合成数据闭环",
    source: "NVIDIA",
    time: "10:10",
    category: "开源项目",
    credibility: 93,
    heat: 86,
    relevance: 90,
    summary: "更新集中在场景生成、物理交互和 Sim2Real 数据管线。",
    why: "对 ROS、仿真、数据闭环能力地图都有直接补强价值。",
    actions: ["看代码", "做项目", "收藏"],
    knowledge: ["Simulation", "Synthetic Data", "Sim2Real"],
    project: "搭建一个简化机械臂仿真数据采集流程图",
  },
  {
    id: 4,
    title: "AI 安全社区讨论 Agent 记忆污染与工具权限边界",
    source: "The Decoder",
    time: "10:45",
    category: "AI安全",
    credibility: 84,
    heat: 82,
    relevance: 80,
    summary: "焦点从单轮提示注入转向长期记忆、文件权限和工具链隔离。",
    why: "适合写成产品风控卡片，也能补充 Agent 系统设计常识。",
    actions: ["写笔记", "收藏"],
    knowledge: ["Prompt Injection", "Memory Safety", "Permissions"],
    project: "设计一个 Agent 权限分级与审计日志原型",
  },
  {
    id: 5,
    title: "新 AI 编程产品主打科研代码复现，从论文到实验脚本",
    source: "Product Hunt AI",
    time: "11:30",
    category: "AI产品",
    credibility: 78,
    heat: 89,
    relevance: 84,
    summary: "产品把论文 PDF、GitHub 仓库和实验配置串成可执行任务流。",
    why: "适合拆成产品分析卡：痛点、核心流程、竞品和商业化边界。",
    actions: ["写笔记", "收藏"],
    knowledge: ["Research Workflow", "AI Coding", "PM Analysis"],
    project: "画一张论文复现助手的信息架构图",
  },
  {
    id: 6,
    title: "arXiv 新论文提出轻量 3D 场景记忆用于移动机器人导航",
    source: "arXiv",
    time: "12:15",
    category: "机器人",
    credibility: 86,
    heat: 77,
    relevance: 91,
    summary: "方法用紧凑场景表征替代全量地图，提升长期导航的检索效率。",
    why: "和 SLAM、视觉导航、移动机器人方向高度相关，适合精读。",
    actions: ["读论文", "写笔记", "做项目", "收藏"],
    knowledge: ["SLAM", "3D Memory", "Navigation"],
    project: "用公开数据集比较稀疏地图和语义地图的检索指标",
  },
];

export const trends = [
  { label: "具身智能", value: 92, delta: "+18%" },
  { label: "多模态 Agent", value: 87, delta: "+12%" },
  { label: "AI 安全", value: 76, delta: "+7%" },
  { label: "开源复现", value: 68, delta: "+5%" },
];

export const readingQueue = [
  "先读 VLA 机器人进展：与你的申请方向最贴近",
  "再看多模态 Agent 成本论文：适合做产品化分析",
  "晚上整理 AI 安全权限边界：可沉淀为案例库",
];

export const applicationMaterials = [
  "VLA 综述素材",
  "Sim2Real 项目想法",
  "Agent 安全产品卡",
  "论文复现实验流程",
];

export const skillMap = [
  { skill: "PyTorch", level: 72 },
  { skill: "ROS", level: 48 },
  { skill: "CV/多模态", level: 64 },
  { skill: "LLM Agent", level: 70 },
  { skill: "产品分析", level: 58 },
];
